---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pvc
  labels:
    name: wp-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: do-block-storage 
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-deploy
  labels:
    name: wp-deploy
spec:
  replicas: 1
  selector:
    matchLabels: 
      name: wp-pod
  template:
    metadata: 
      name: wp-pod
      labels:
        name: wp-pod
    spec:
      volumes:
      - name: wp-vol
        persistentVolumeClaim:
          claimName: wp-pvc
      containers:
      - name: wp-container
        image: wordpress:5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: wp-cm
        - secretRef:
            name: wp-secret
        volumeMounts:
        - name: wp-vol
          mountPath: /var/www/html

---
apiVersion: v1
kind: Service
metadata:
  name: wp-svc
  labels:
    name: wp-svc
spec:
  type: ClusterIP
  selector:
    name: wp-pod
  ports:
  - port: 80
    targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wp-ing
  labels:
    name: wp-ing
  annotations:
    nginx.ingress.kubernetes.io/limit-connections: "5"
spec:
  ingressClassName: nginx
  rules:
  - host: tenant.163.47.10.239.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wp-svc
            port:
              number: 80

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: wp-netpol
  labels:
    name: wp-netpol
spec:
  podSelector:
    matchLabels:
      name: wp-pod
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from: 
    - namespaceSelector: 
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
          name: ingress-nginx
      podSelector:
        matchLabels:
          app.kubernetes.io/component: controller
          app.kubernetes.io/instance: ingress-nginx
          app.kubernetes.io/name: ingress-nginx
  egress:
  - to:
    - podSelector:
        matchLabels:
          name: wpdb-db
    ports:
    - port: 3306
      protocol: TCP
  - ports:
    - port: 53
      protocol: TCP
    - port: 53
      protocol: UDP