---
apiVersion: v1
kind: Secret
metadata:
  name: wp-secret
  labels:
    name: wp-secret
data:
  # wordpress
  ROOT_PASSWORD: d29yZHByZXNz
  WORDPRESS_DB_PASSWORD: d29yZHByZXNz

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wp-cm
  labels:
    name: wp-cm
data:
  WORDPRESS_DB_HOST: wpdb-cluster-mysql-master
  WORDPRESS_DB_USER: root
  WORDPRESS_DB_NAME: wpdb

---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
   name: wpdb-cluster
   labels:
      name: wpdb-cluster
spec:
   replicas: 2
   secretName: wp-secret
   volumeSpec:
    persistentVolumeClaim:
      accessModes:
      - ReadWriteOnce
      storageClassName: do-block-storage 
      resources:
         requests:
            storage: 1Gi

---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlDatabase
metadata:
   name: wpdb-db
   labels:
      name: wpdb-db
spec:
   database: wpdb
   clusterRef:
      name: wpdb-cluster
